apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 10
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/depot-argocd-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: APP_VERSION
              value: v1
          image: believer2001/monapp:v1
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 5000
            #  hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
