Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "vm1-manager" do |manager|
    manager.vm.hostname = "vm1-manager"
    manager.vm.network "private_network", ip: "192.168.58.10"
    manager.vm.provider "vmware_desktop" do |v|
      v.memory = "1024"
      v.cpus = 2
    end
  end

  config.vm.define "vm2-worker" do |worker|
    worker.vm.hostname = "vm2-worker"
    worker.vm.network "private_network", ip: "192.168.58.11"
    worker.vm.provider "vmware_desktop" do |v|
      v.memory = "1024"
      v.cpus = 1
    end
  end
end