---
- name: Déployer la pile de monitoring Prometheus & Grafana sur Kubernetes
  hosts: masters
  become: yes          
  gather_facts: false

  tasks:
    - name: Installer Python3-pip et la bibliothèque Kubernetes sur le master
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-kubernetes
          - curl          # Nécessaire pour télécharger le script d'installation de Helm
        state: present
        update_cache: yes

    - name: Installer Helm (gestionnaire de paquets Kubernetes)
      ansible.builtin.shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Créer le namespace monitoring
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: monitoring
        state: present

    - name: Ajouter le dépôt Helm Prometheus Community
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Installer ou mettre à jour la stack kube-prometheus via Helm
      kubernetes.core.helm:
        name: monitoring-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        state: present
        values:
          grafana:
            service:
              type: ClusterIP
          prometheus:
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false